"""本地最小类型 stub：matplotlib.pyplot（只覆盖项目实际用到的函数）。

matplotlib 自带的部分类型标注带 **kwargs: Unknown，strict 模式下每个
plt.* 调用都会报 reportUnknownMemberType；社区 matplotlib-stubs 实测
反而更差。这里用本地 stub 覆盖 pyplot 模块：能写真实的类型就写真实
类型，仅在 matplotlib 动态 API 无法精确处保留 Any。

保留 Any 的原因：
- *args 与数据类参数（plot 的 x/y、bar 的 x/height、scatter 的 x/y、
  text 的 x/y、hist 的 x、xticks 的 ticks/labels）：matplotlib 接受任意
  array-like（含 pandas 的 Index/Series），其 ArrayLike 类型无法容纳
  pandas-stubs 的联合类型，写死会误报。
- **kwargs（plot/xticks/hist/axvline/axhline/bar）：matplotlib 的 Artist
  属性都是合法关键字参数（label/color/marker/linestyle/rotation/
  edgecolor…），属动态属性 API，无法穷举。
- gca() -> Any：真实 Axes.xaxis.set_major_formatter 的参数无类型注解，
  写 Axes 会重新触发 reportUnknownMemberType。
"""

from collections.abc import Sequence
from typing import Any

from matplotlib.artist import Artist
from matplotlib.collections import PathCollection
from matplotlib.container import BarContainer
from matplotlib.figure import Figure
from matplotlib.legend import Legend
from matplotlib.lines import Line2D
from matplotlib.text import Text


def figure(figsize: tuple[float, float] | None = None) -> Figure: ...


def plot(*args: Any, **kwargs: Any) -> list[Line2D]: ...
def title(label: str) -> Text: ...
def xlabel(xlabel: str) -> Text: ...
def ylabel(ylabel: str) -> Text: ...
def legend(handles: Sequence[Artist] | None = None) -> Legend: ...
def xticks(
    ticks: Any = None,
    labels: Any = None,
    **kwargs: Any,
) -> tuple[Any, list[Text]]: ...
def ylim(
    bottom: float | None = None,
    top: float | None = None,
) -> tuple[float, float]: ...
def grid(visible: bool | None = None) -> None: ...
def tight_layout() -> None: ...
def show(*, block: bool | None = None) -> None: ...
def close(fig: Figure | None = None) -> None: ...
def gcf() -> Figure: ...
def gca() -> Any: ...
def hist(
    x: Any,
    bins: int | Sequence[float] | str | None = None,
    **kwargs: Any,
) -> tuple[Any, Any, Any]: ...
def axvline(x: float = 0, **kwargs: Any) -> Line2D: ...
def axhline(y: float = 0, **kwargs: Any) -> Line2D: ...
def bar(x: Any, height: Any, **kwargs: Any) -> BarContainer: ...
def scatter(x: Any, y: Any) -> PathCollection: ...
def text(x: Any, y: Any, s: str) -> Text: ...
