"""本地最小类型 stub：matplotlib.pyplot。

matplotlib 自带的部分类型标注带有 **kwargs: Unknown，在 strict 模式下
会让每个 plt.* 调用都报 reportUnknownMemberType。这里用本地 stub 覆盖
pyplot 模块，参数放宽为 Any，消除噪音且不弱化任何 strict 规则。
"""

from typing import Any

from matplotlib.figure import Figure


def figure(
    num: int | str | Figure | None = None,
    figsize: tuple[float, float] | None = None,
    dpi: float | None = None,
    **kwargs: Any,
) -> Figure: ...


def plot(*args: Any, **kwargs: Any) -> Any: ...
def title(label: str, **kwargs: Any) -> Any: ...
def xlabel(xlabel: str, **kwargs: Any) -> Any: ...
def ylabel(ylabel: str, **kwargs: Any) -> Any: ...
def legend(*args: Any, **kwargs: Any) -> Any: ...
def xticks(*args: Any, **kwargs: Any) -> Any: ...
def ylim(bottom: float | None = None, top: float | None = None, **kwargs: Any) -> Any: ...
def grid(visible: bool | None = None, **kwargs: Any) -> None: ...
def tight_layout(*args: Any, **kwargs: Any) -> None: ...
def show(*, block: bool | None = None, **kwargs: Any) -> None: ...
def close(fig: Figure | None = None) -> None: ...
def gcf() -> Figure: ...
def gca() -> Any: ...
def hist(x: Any, **kwargs: Any) -> Any: ...
def axvline(x: float = 0, **kwargs: Any) -> Any: ...
def axhline(y: float = 0, **kwargs: Any) -> Any: ...
def bar(x: Any, height: Any, **kwargs: Any) -> Any: ...
def scatter(x: Any, y: Any, **kwargs: Any) -> Any: ...
def text(x: Any, y: Any, s: str, **kwargs: Any) -> Any: ...
